---
version: '2'
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - ginkgolinter
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: add-constant
          arguments:
            - allowInts: 0,1,2,3
              allowStrs: '""'
              ignoreFuncs: assert\.Len,require\.Len
              maxLitCount: '5'
        - name: line-length-limit
          arguments:
            - 120
          severity: warning
          exclude:
            - ''
        - name: comment-spacings
        - name: indent-error-flow
        - name: use-errors-new
        - name: bare-return
        - name: cognitive-complexity
          disabled: true
        - name: context-as-argument
        - name: cyclomatic
          disabled: true
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: exported
        - name: function-length
          disabled: true
        - name: if-return
        - name: import-alias-naming
        - name: import-shadowing
        - name: increment-decrement
        - name: max-control-nesting
        - name: max-public-structs
          arguments:
            - 14
        - name: redefines-builtin-id
        - name: receiver-naming
        - name: redundant-import-alias
        - name: struct-tag
        - name: superfluous-else
        - name: unchecked-type-assertion
        - name: unexported-naming
    staticcheck:
      checks:
        - all
        - '-ST1000'
        - '-ST1003'
        - '-ST1016'
        - '-SA1019'
        - '-ST1020'
        - '-ST1021'
        - '-ST1022'
formatters:
  enable:
    - gofmt
    - goimports