name: Build and release image

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  CLI_IMAGE: ghcr.io/belastingdienst/opr-paas-cli

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  version:
    name: Normalize version
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      version: ${{ steps.export.outputs.version }}

    steps:
      - name: Determine version
        id: export
        run: |
          CLEANED="${GITHUB_REF_NAME#v}"
          echo "version=${CLEANED}" >> $GITHUB_OUTPUT

  image:
    name: Push image to ghcr.io
    runs-on: ubuntu-latest
    needs: [version]
    permissions:
      packages: write
      contents: write
    env:
      VERSION: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Login to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: opr-paas-meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            name=${{ env.CLI_IMAGE }},enable=true
          tags: |
            type=raw,value=v${{ env.VERSION }}
            type=raw,value=latest
            type=sha

      - name: Build and push image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ${{ steps.opr-paas-meta.outputs.tags }}
          labels: ${{ steps.opr-paas-meta.outputs.labels }}
          build-args: VERSION=${{ env.VERSION }}

      - name: Generate kubectl-paas image SBOM
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: '${{ env.CLI_IMAGE }}:v${{ env.VERSION }}'
          scan-type: image
          format: 'github'
          output: 'paas-cli_image.sbom.json'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          severity: 'MEDIUM,HIGH,CRITICAL'
          scanners: 'vuln'
        env:
          TRIVY_SKIP_DB_UPDATE: true
          TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Add SBOM to release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: '${{ github.workspace }}/paas-cli_image.sbom.json'
